src/blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView
)

app_name = 'posts'
urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('<slug:slug>/', PostDetailView.as_view(), name='detail'),
]

src/nhome/urls.py
from django.contrib import admin
from blog import views as blog_views
from django.urls import path, include
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', blog_views.home, name='home'),
    path('posts/', include('blog.urls', namespace='posts')),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="accounts/logout.html"), name='logout'),
    path('register/', accounts_views.register, name='register'),
    path('admin/', admin.site.urls),
]

src/accounts/models.py
from django.db import models

# Create your models here.

src/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User

class Post(models.Model):
    author      = models.ForeignKey(User, on_delete=models.CASCADE)
    title       = models.CharField(max_length=255, null=False)
    slug        = models.SlugField(max_length=255, null=False, unique=True)
    content     = models.TextField(null=False)
    draft       = models.BooleanField()
    #readtime    = models.IntegerField()
    #published   = models.DateTimeField('Published at')
    created     = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'slug': self.slug})

class Comment(models.Model):
    author      = models.ForeignKey(User, on_delete=models.CASCADE)
    post        = models.ForeignKey(Post, on_delete=models.CASCADE)
    content     = models.TextField(null=False)
    created     = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.content

src/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]

src/accounts/views.py
from .forms import UserRegisterForm
from django.contrib import messages
from django.shortcuts import render, redirect

def register(request):
    form = UserRegisterForm(request.POST or None)

    if form.is_valid():
        form.save()

        messages.info(request, f'Your account has been created successfully. An e-mail has been sent to confirm your registration.')
        return redirect('home')

    context = {
        'form': form,
    }

    return render(request, 'accounts/register.html', context)

def login(request):
    context = {}

    return render(request, 'accounts/login.html', context)

src/blog/views.py
from blog.models import Post
from django.views import generic
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

def home(request):

    context = {
        'posts': Post.objects.order_by('-created')[:5],
    }
    return render(request, "blog/home.html", context)

class PostListView(generic.ListView):
    context_object_name = 'posts'

    ordering = [
        '-created',
    ]

    paginate_by = 5

    model = Post


class PostDetailView(generic.DetailView):
    context_object_name = 'post'
    model = Post

class PostCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    fields = [
        'title',
        'content',
        'draft',
        #'published'
    ]

    success_message = f'Your post has been created successfully.'
    model = Post

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    fields = [
        'title',
        'content',
        'draft',
        #'published'
    ]

    success_message = f'Your post has been updated successfully.'
    model = Post

src/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-4">
    <h4 class="display-4">Sign In</h4>
    <form action="{% url 'login' %}" method="POST" novalidate>{% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Sign In</button>
            <a href="#" class="btn btn-link">Forgot your password?</a>
        </div>
        <div class="text-muted">
            Need an account?
            <a href="{% url 'register' %}">Sign Up Now</a>
        </div>
    </form>
</div>
{% endblock content %}

src/templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-8">
    <p class="lead">You have been logged out successfully. Would you like to <a href="{% url 'login' %}">login</a> again</p>
</div>
{% endblock content %}

src/templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-8">
    <h4 class="display-4">Join Today</h4>
    <form action="{% url 'register' %}" method="POST" novalidate>{% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Sign Up</button>
            <div class="text-muted">
                Already have an account?
                <a href="{% url 'login' %}">Sign In</a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

src/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% block stylesheets %}{% endblock stylesheets %}
        <title>{% block title %}ProjectName{% endblock title %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
            <a class="navbar-brand mb-1 h1" href="{% url 'home' %}">ProjectName</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:list' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'posts:create' %}">New Post</a>
                        <a class="dropdown-item" href="#">Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            </div>
        </nav>
        <main role="main">
            {% block jumbotron %}{% endblock jumbotron %}
            <div class="container">
                {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                {% endif %}
                <div class="row justify-content-center">
                {% block content %}{% endblock content %}
                {% block sidebar %}{% endblock sidebar %}
                </div> <!-- .row -->
            </div> <!-- .container -->
        </main>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        {% block scripts %}{% endblock scripts %}
    </body>
</html>

src/templates/blog/home.html
{% extends 'base.html' %}
{% block jumbotron %}
{% if user.is_anonymous %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-4">Welcome!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="{% url 'register' %}" role="button">Sign Up Now</a>
    </div>
</div>
{% endif %}
{% endblock jumbotron %}
{% block content %}
        <div class="col-md-8">
            <h2>Homepage</h2>
        </div>
{% endblock content %}
{% block sidebar %}
    <aside class="col-md-4 blog-sidebar">
        <div class="p-4">
            <h4 class="font-italic">Recent Posts</h4>
            <ol class="list-unstyled mb-0">
            {% for post in posts %}
            <li><a href="{% url 'posts:detail' post.slug %}">{{ post.title }}</a></li>
            {% endfor %}
            </ol>
        </div>
    
        <div class="p-4">
            <h4 class="font-italic">Elsewhere</h4>
            <ol class="list-unstyled">
            <li><a href="https://github.com/duncan-f" target="_blank">GitHub</a></li>
            <li><a href="#" target="_blank">Twitter</a></li>
            <li><a href="#" target="_blank">Facebook</a></li>
            </ol>
        </div>
    </aside><!-- /.blog-sidebar -->
{% endblock sidebar %}

src/templates/blog/post_detail.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-8">
    <h4 class="display-4">{{ post.title }}</h4>
    <p><small>{{ post.author }}</small></p>
    <p><a href="{% url 'posts:update' post.id %}">Update</a></p>
    <p class="lead">{{ post.content }}</p>
</div>
{% endblock content %}

src/templates/blog/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-8">
    <h1 class="display-4">Blog Post</h1>
    <form method="POST" novalidate>{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Publish</button>
    </form>
</div>
{% endblock content %}

src/templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-8">
    <h1 class="display-4">All Posts</h1>
    {% for post in posts %}
        <a href="{% url 'posts:detail' post.slug %}">{{ post.title }}</a>, by {{ post.author }}
        <p class="lead">{{ post.content|truncatechars:120 }}</p>
    {% endfor %}
    {% if is_paginated %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">
                            {{ num }}
                            <span class="sr-only">(current)</span>
                        </span>
                    </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next</span>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock content %}
{% block sidebar %}
    <aside class="col-md-4 blog-sidebar">
    <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
    </div>

    <div class="p-4">
        <h4 class="font-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
        <li><a href="#">March 2014</a></li>
        <li><a href="#">February 2014</a></li>
        <li><a href="#">January 2014</a></li>
        <li><a href="#">December 2013</a></li>
        <li><a href="#">November 2013</a></li>
        <li><a href="#">October 2013</a></li>
        <li><a href="#">September 2013</a></li>
        <li><a href="#">August 2013</a></li>
        <li><a href="#">July 2013</a></li>
        <li><a href="#">June 2013</a></li>
        <li><a href="#">May 2013</a></li>
        <li><a href="#">April 2013</a></li>
        </ol>
    </div>

    <div class="p-4">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled">
        <li><a href="#">GitHub</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
        </ol>
    </div>
    </aside><!-- /.blog-sidebar -->
{% endblock sidebar %}